"model":
  "type": "DFNet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "L": 5
    "k": 12

"optimizer":
  "type": "AdamW"
  "params":
    "lr": 0.001

"lr_scheduler":
  "type": "MultiStepLR"
  "params":
    "milestones": [5, 15, 25, 35]
    "gamma": 0.2

"dataset":
  "train":
    "type": "cleargrasp-syn"
    "data_dir": "data-cleargrasp"
    "image_size": !!python/tuple [320, 240]
    "use_augmentation": True
    "rgb_augmentation_probability": 0.8
  "test":
    "type": "transparent-object"
    "data_dir": "data-keypose"
    "image_size": !!python/tuple [320, 240]
    "use_augmentation": False

"dataloader":
  "num_workers": 72
  "shuffle": True
  "drop_last": True

"trainer":
  "batch_size": 64
  "test_batch_size": 1
  "multigpu": True
  "max_epoch": 40  
  "criterion":
    "type": "custom_masked_mse_loss"
    "epsilon": 0.00000001

"metrics":
  "types": ["MSE", "MaskedMSE", "RMSE", "MaskedRMSE", "REL", "MaskedREL", "MAE", "MaskedMAE", "Threshold@1.05", "MaskedThreshold@1.05", "Threshold@1.10", "MaskedThreshold@1.10", "Threshold@1.25", "MaskedThreshold@1.25"]
  "epsilon": 0.00000001

"stats":
  "stats_dir": "stats"
  "stats_exper": "small-cg"
